name: CI

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of ROM/Firmware"
        required: true

env:
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  GIT_ORG_NAME: Van-Firmware-Dumps
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: @VanFirmwareDumps
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkouts
        uses: actions/checkout@v4
        
      - name: Dump
        run: |
          mkdir -p ~/job && cd ~/job
          git clone https://github.com/VanVuong41429/Van-DumprX.git DumprX
          cd DumprX
          sudo bash ./setup.sh || exit 1
          sudo apt install -y f2fs-tools neofetch
          echo "$GIT_TOKEN" > .github_token
          echo "$GIT_ORG_NAME" > .github_orgname
          echo "$BOT_TOKEN" > .tg_token
          echo "$CHAT_ID" > .tg_chat
          ./dumper.sh "${ROM_URL}" || exit 1

          echo test, and deploy your project.
