name: CI

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of ROM/Firmware"
        required: true

env:
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  GIT_ORG_NAME: "DroidDumps"
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Dump
        run: |
          mkdir -p ~/job && cd ~/job
          git clone https://github.com/DroidDumps/phoenix_firmware_dumper -b rokibhasansagar-patch-1
          cd phoenix_firmware_dumper
          sudo bash ./setup.sh || exit 1
          echo "$GIT_TOKEN" > .github_token
          echo "$GIT_ORG_NAME" > .github_orgname
          echo "$BOT_TOKEN" > .tg_token
          echo "$CHAT_ID" > .tg_chat
          ./dumper.sh "${ROM_URL}" || exit 1

          echo test, and deploy your project.
