name: DumprX on GITGUD
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Checkouts
         uses: actions/checkout@v4

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/Van-Firmware-Dumps/DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |

              sudo bash setup.sh
              sudo apt install -y f2fs-tools neofetch
              mkdir -p ~/.ssh
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              ssh-keyscan -t rsa gitgud.io >> ~/.ssh/known_hosts
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              echo "${{ secrets.GITGUD_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "Van-Firmware-Dumps" > .gitlab_group  # Only for Gitlab
              echo "gitgud.io" > .gitlab_instance  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_rsa  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat
              chmod 600 ~/.ssh/id_rsa

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: DumprX
         run: |
              wget --no-check-certificate -O firmware.zip 'https://mirrors.lolinet.com/firmware/lenowow/Tab_M10_5G/TB360ZU/TB360ZU_ROW_OPEN_USER_Q00024.0_T_ZUI_15.0.776_ST_240417.zip' > /dev/null 2>&1
              7z e -y firmware.zip -ofirmware > /dev/null 2>&1 && rm firmware.zip firmware/*rawprogram*
              cd firmware && mv super_1.img super.img && mv super_2.img odm.img && mv super_3.img product.img && super_4.img system.img && mv super_5.img system_ext.img && mv super_6.img vendor.img && cd ..
              zip -r firmware.zip firmware > /dev/null 2>&1 && rm -rf firmware
              ./dumper.sh "$ROM_URL"
