name: DumprX on GITGUD
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Checkouts
         uses: actions/checkout@v4

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/Van-Firmware-Dumps/DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |

              sudo bash setup.sh
              sudo apt install -y f2fs-tools neofetch
              mkdir -p ~/.ssh
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              ssh-keyscan -t rsa gitgud.io >> ~/.ssh/known_hosts
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              echo "${{ secrets.GITGUD_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "Van-Firmware-Dumps" > .gitlab_group  # Only for Gitlab
              echo "gitgud.io" > .gitlab_instance  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_rsa  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat
              chmod 600 ~/.ssh/id_rsa

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD
              aria2c -x16 -s8 --console-log-level=warn --summary-interval=0 --check-certificate=false -o firmware.zip "https://mirrors-obs-2.lolinet.com/firmware/lenomola/2019/channel/official/RETEU/XT1952-1_CHANNEL_RETEU_10_QPYS30.52-22-8-9_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip"
              7z e -y -ofirmware "firmware.zip" && rm firmware.zip
              ./utils/bin/simg2img firmware/*system*chunk* firmware/system.img.raw && ./utils/bin/simg2img firmware/*vendor*chunk* firmware/vendor.img.raw
              rm firmware/*system*chunk* firmware/*vendor*chunk*
              mv firmware/system.img.raw firmware/system.img && mv firmware/vendor.img.raw firmware/vendor.img
              zip -r firmware.zip firmware && rm -rf firmware

       - name: Start Dumping
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
